spring.application.name=final_project
spring.datasource.url=jdbc:mysql://localhost:3306/CampusConnect
spring.datasource.username=root
spring.datasource.password=MySQLlogin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.docker.compose.enabled=false